apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nft-create-solana
  name: nft-create-solana
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nft-create-solana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nft-create-solana
    spec:
      containers:
      - image: "{{ .Values.image }}" 
        name: nft-create-solana
        command: ["/bin/bash","-c","npm run-script start"]
        resources: {}
status: {}
